# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea19b0fc243dbbc6085789c0820f2c147d6549b753017275e6f34debb7e772ea1d2ec39ee0709797daefc18ea8e0e8ccca19a7df1fe22df8af68b2af1567e83

test:
  secret_key_base: 307b9c4fbc04fe3d860f8ef1a41b9108456db1a0d6426e3f441679e9b1add27fbf7854baae931e3e0a88c78c67a1c35fd51f4a147638eaa12ca78d464031b039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
